### ISSUE TITLE
small issue if xliffsOut dir does not exist

### ISSUE THREAD

**Issue by peterfarrant** [iLib-js/loctool#162]
Not a significant item but if the 
xliffsOut directory does not exist you get the following:
(it would be nice if it created the directory if it did not exist like the targetDir)

```
16:53:34 INFO loctool.lib.Project: Writing out the extracted strings to xliff2\reseller-extracted.xliff
16:53:34 ERROR loctool.loctool: caught exception: Error: ENOENT: no such file or directory, open 'xliff2\reseller-extracted.xliff'
16:53:34 ERROR loctool.loctool: Error: ENOENT: no such file or directory, open 'xliff2\reseller-extracted.xliff'
    at Object.openSync (fs.js:476:3)
    at Object.writeFileSync (fs.js:1467:35)
    at CustomProject.Project.close (C:\Code\Documentation\loctool\lib\Project.js:649:16)
    at C:\Code\Documentation\loctool\loctool.js:398:33
    at CustomProject.Project.save (C:\Code\Documentation\loctool\lib\Project.js:467:5)
    at C:\Code\Documentation\loctool\loctool.js:397:29
    at CustomProject.<anonymous> (C:\Code\Documentation\loctool\lib\Project.js:534:9)
    at LocalRepository.getBy (C:\Code\Documentation\loctool\lib\LocalRepository.js:130:5)
    at CustomProject.Project.write (C:\Code\Documentation\loctool\lib\Project.js:513:13)
    at C:\Code\Documentation\loctool\loctool.js:396:25
16:53:34 INFO loctool.loctool: Done
```

Quite happy for you to close the issue if you think not important

**Comment by ehoogerbeets** [comment]
That's an easy one to fix. Above is the link to the PR for it.

**Comment by peterfarrant** [comment]
thanks - only catches me out the first time I do a project
