### ISSUE TITLE
Trouble running tests out of the box

### ISSUE THREAD

**Issue by cbetta** [iLib-js/loctool#47]
I've been trying to run the tests for this project and I'm running into a few issues.

Firstly, as my machine is not set to `en_US` a few tests fail. I'd recommend running the tests explicitly with this locale in `package.json`

```
"test": "cd test; LANG=en_US node testSuite.js"
```

Secondly, it seems a few dependencies are missing to run the tests.

```
"devDependencies": {
  "ilib-loctool-javascript": "^1.0.0",
  ...
}
```

Finally, even after this I get 2 errors:

```sh
$ cd test; LANG=en_US node testSuite.js
androidflavors: ................
androidlayoutfile: .........................
androidlayoutfiletype: ................
androidproject: ....
androidresourcefile: ........................
androidresourcefiletype: ..................................
buildgradle: ................
customproject: .....FF...........
AssertionError: false == true
    at Object.ok (/Users/cbetta/code/box/loctool/node_modules/nodeunit/lib/types.js:83:39)
    at /Users/cbetta/code/box/loctool/test/testCustomProject.js:141:18
    at CustomProject.<anonymous> (/Users/cbetta/code/box/loctool/lib/Project.js:173:13)
    at LocalRepository.getLocales (/Users/cbetta/code/box/loctool/lib/LocalRepository.js:185:5)
    at CustomProject.<anonymous> (/Users/cbetta/code/box/loctool/lib/Project.js:158:17)
    at LocalRepository.init (/Users/cbetta/code/box/loctool/lib/LocalRepository.js:73:5)
    at CustomProject.Project.init (/Users/cbetta/code/box/loctool/lib/Project.js:154:13)
    at Object.testCustomProjectRightResourceTypeJavascript (/Users/cbetta/code/box/loctool/test/testCustomProject.js:138:11)
    at Object.<anonymous> (/Users/cbetta/code/box/loctool/node_modules/nodeunit/lib/core.js:236:16)
    at /Users/cbetta/code/box/loctool/node_modules/nodeunit/lib/core.js:236:16

AssertionError: false == true
    at Object.ok (/Users/cbetta/code/box/loctool/node_modules/nodeunit/lib/types.js:83:39)
    at /Users/cbetta/code/box/loctool/test/testCustomProject.js:191:18
    at CustomProject.<anonymous> (/Users/cbetta/code/box/loctool/lib/Project.js:173:13)
    at LocalRepository.getLocales (/Users/cbetta/code/box/loctool/lib/LocalRepository.js:185:5)
    at CustomProject.<anonymous> (/Users/cbetta/code/box/loctool/lib/Project.js:158:17)
    at LocalRepository.init (/Users/cbetta/code/box/loctool/lib/LocalRepository.js:73:5)
    at CustomProject.Project.init (/Users/cbetta/code/box/loctool/lib/Project.js:154:13)
    at Object.testCustomProjectRightResourceTypeJS (/Users/cbetta/code/box/loctool/test/testCustomProject.js:188:11)
    at Object.<anonymous> (/Users/cbetta/code/box/loctool/node_modules/nodeunit/lib/core.js:236:16)
    at /Users/cbetta/code/box/loctool/node_modules/nodeunit/lib/core.js:236:16

htmlfile: ...............................................................................
htmlfiletype: .........
htmltemplatefile: .......................................................................................................
htmltemplatefiletype: .........
hamlfile: ............................................................................................................................................................................................
hamlfiletype: ...........
stringsfile: .........(node:98747) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
...........
stringsfiletype: .................................
javafile: ........................................................
javafiletype: .....
scriptfile: ..........................................
scriptfiletype: ......................
scriptresourcefile: ............................
scriptresourcefiletype: ......
jsxfile: ................................
jsxfiletype: ................
localrepository: .......................
markdown: ..........................................................................................................
markdownfiletype: ................
objectivecfile: ............................
objectivecfiletype: ......
oldhamlfiletype: .........
projectfactory: ....
pseudobritish: .......................
pseudocanadian: ....................
pseudofactory: ..................................
pseudohant: ...............
pseudonz: ...................
resource: .......................
resourcearray: ............................................................
ResourceFactory: ..........
resourceplural: ........................................................
resourcestring: ........................................................
rubyfile: .............................................................................
rubyfiletype: .............
set: .......................
swiftfile: .............................
swiftfiletype: ......
translationset: ...................................................................
utils: ...............
webproject: ..............
xliff: ......................................................................
yamlfile: ..................................................................
yamlfiletype: .............
yamlresourcefile: ......................
yamlresourcefiletype: .........................

FAILURES: 2/6917 assertions failed (3741ms)
error Command failed with exit code 1.
```

**Comment by ehoogerbeets** [comment]
Resolved
